package com.machidior.Loan_Management_Service.enums;

public enum PenaltyCalculationMethod {
    FLAT_AMOUNT,
    PERCENTAGE_OF_OVERDUE_AMOUNT,
    PERCENTAGE_OF_INSTALLMENT,
    PERCENTAGE_OF_PRINCIPAL_OUTSTANDING,
    PERCENTAGE_OF_TOTAL_OUTSTANDING,
    PERCENTAGE_OF_LOAN_AMOUNT
}